In [9]:
#question-> is there a relationship between survival and gender in titanic.

## null hypothesis (Ho) ---> There is no relationship
## alternate hypothesis (H1) ---> There is a relationship

In [10]:
import numpy as np 
import seaborn as sns    #----------------> for inbuilt titanic data set
from scipy.stats import chi2_contingency #---------->for chi2 functions
import pandas as pd

In [11]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
contingency_table = pd.crosstab(df['sex'],df['survived']) #------------> or observed frequency
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [13]:
chi2, p_value , dof , expected = chi2_contingency(contingency_table) #----> this fn return 4 values a tuple

print("Chi square value = ",chi2)
print("p value = ", p_value)
print("degree of freedom = ", dof)
print("Expected frequency = ",expected)

Chi square value =  260.71702016732104
p value =  1.1973570627755645e-58
degree of freedom =  1
Expected frequency =  [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [14]:
alpha = 0.05     #------> significant value given

In [15]:
if p_value < alpha:
    print("we reject the null hypothesis and there is a significant relationship between gender and survivl")
else:
    print("we accept the null hypothesis , there is no connenction")

we reject the null hypothesis and there is a significant relationship between gender and survivl